import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AppProvider from "@/app/app-provider";
import SlideSession from "@/components/slide-session";
import ImageViewer from "@/components/image-viewer";

const roboto = Roboto({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Chatbot",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Toaster richColors position="top-right" />
        <ImageViewer />
        {/* {children} */}
        <AppProvider>
          {children}
          <SlideSession />
        </AppProvider>
      </body>
    </html>
  );
}
